### PR TITLE
Library updates continued

### PR DESCRIPTION
**Pull request by jersmi7**
Uploaded to Jersmi/utilities

(R. Meyer collabs)
Pitch Wheel
Tuning Wheel
Tunings Tile
Quantizer Tile (raga)

Conversions Tile (common math conversions)
Comment Tile (make a colored comment box in your patch)

Updates to Matrix 4x4 and 8x8

### CODE REVIEW

**Comment by jersmi7** [comment]
Forgot one -- Chebyshev VCO. Stanley reminded me. :)

**Comment by jersmi7** [comment]
Update to VCF multimode module to fix a Lua error. Also fixed keyword, mislabelled as "Instrument" instead of "VCF".

The error
Canvas audio meter light -- issue assigning a port value to alpha in a r,g,b,a table color. In this fix I just declared the alpha variable to prevent the nil error. Weird, not seeing it elsewhere even though I have been using the exact same canvas Lua throughout a bunch of updated modules. Port values should immediately initialize anything the port value is assigned to in Lua, no?

**Comment by jersmi7** [comment]
Why the branch conflicts sometimes but most of the time deleting existing / adding new files works fine?

Anyway, two more updates:
• Spectrum Analyzer updated, now with tags. 
• Gain dB module updated with (new) canvas RMS and peak metering. (This will eventually go into the 6 ch mixer, which is getting an update, slowly, and imho meters something like this should be standard for audio output modules.)

**Comment by wtholliday** [comment]
> Why the branch conflicts sometimes but most of the time deleting existing / adding new files works fine?

Dunno. But I resolved the conflict. Just check to make sure everything looks good in the next beta :)

**Pull request merged**
